spring.application.name=champions_Call

spring.datasource.url=jdbc:mysql://localhost:3306/Spring_Champion_Call
spring.datasource.username=root
spring.datasource.password=sarthak745

#JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
